name: test Builder
on:
  workflow_dispatch

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

jobs:
  build_wheels:
    name: Build ${{ matrix.python }}-${{ matrix.os }}-${{ matrix.cibw_archs }}
    runs-on: ${{ matrix.cibw_archs || matrix.os }}
    defaults:
      run:
        shell: bash
    strategy:
      fail-fast: false
      matrix:
        python: [cp38]
        # python: [cp38, cp39, cp310, cp311]
        os: [ubuntu-20.04, windows-latest, macos-11]
        include:
          - os: ubuntu-20.04
          - os: windows-latest
          - os: macos-11
    steps:
      - name: Checkout
        uses: actions/checkout@v3
    
      - name: Build/Test/Package
        env:
          CIBW_ARCHS: ${{ matrix.cibw_archs }}
          CIBW_BUILD: ${{matrix.python}}-*
          CIBW_BUILD_VERBOSITY: 1
          # containerized Linux builds require explicit CIBW_ENVIRONMENT
          CIBW_ENVIRONMENT: CFLAGS='-O3 -g0 -mtune=generic -pipe -fPIC' LDFLAGS='-fPIC'
          CIBW_TEST_REQUIRES: pytest
          CIBW_TEST_COMMAND: pytest {package}/tests
        run: |
          pip install -U --user cibuildwheel
          python -m cibuildwheel --platform auto --output-dir dist .


