name: Tests
on: [push]
jobs:
  tests:
    name: ${{ matrix.python-version }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: [3.8, "3.10", "3.11", "3.13"]
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: pip deps
        run: |
          pip install cython setuptools
          python setup.py build_ext -i
      - name: runtests
        run: python tests.py
